# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcontacts' : '@latest'
    'frameworks/prison' : '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/kmime' : '@same'
    'kde/pim/libkleo' : '@same'
    'kde/pim/grantleetheme' : '@same'
    'third-party/grantlee' : '@stable'
