# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts' : '@latest-kf6'
    'frameworks/prison' : '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/kmime' : '@same'
    'pim/grantleetheme' : '@same'
    'frameworks/ktexttemplate': '@stable'
    'libraries/ktextaddons': '@latest-kf6'
