# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts' : '@latest-kf6'
    'frameworks/prison' : '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'pim/akonadi' : '@latest-kf6'
    'pim/kmime' : '@latest-kf6'
    'pim/grantleetheme' : '@latest-kf6'
    'libraries/ktexttemplate': '@stable'
